### ISSUE TITLE
Stock.csv

### ISSUE THREAD

**Issue by soninikul007** [QueryType/bharattrader#1]
Hi, 

can you please also share stock.csv file that you use as an input or tell us where do you find the stocks name.

**Comment by Harshitjan11** [comment]
Hi Bharat Sir, 
can you please share a sample format for stock.csv file. so that we can add our stocks in it accordingly

**Comment by QueryType** [comment]
Something like this...
Ticker,
SIGACHI,
GATI,
DONEAR,
IDBI,
APTECHT,

**Comment by QueryType** [comment]
Sample provided above.
