### ISSUE TITLE
Error while running Ars_Srs python script

### ISSUE THREAD

**Issue by soninikul007** [QueryType/bharattrader#2]
Hello, 

 I get the issue shown below while running the script ars_srs_scan.py

Name: Security Id, dtype: object
TTKHEALTH.NS: No data found, symbol may be delisted
EMPIND.NS: No data found, symbol may be delisted
ALEXANDER.NS: No data found, symbol may be delisted
Error: ALEXANDER => index 0 is out of bounds for axis 0 with size 0
SVARTCORP.NS: No data found, symbol may be delisted
KRYPTONQ.NS: No data found, symbol may be delisted
Error: SINDHUTRAD => index 0 is out of bounds for axis 0 with size 0
PANTH.NS: No data found, symbol may be delisted
Error: PANTH => index 0 is out of bounds for axis 0 with size 0
GALACTICO.NS: No data found, symbol may be delisted
Error: GALACTICO => index 0 is out of bounds for axis 0 with size 0
JANUSCORP.NS: No data found, symbol may be delisted
Error: JANUSCORP => index 0 is out of bounds for axis 0 with size 0
BILLWIN.NS: No data found, symbol may be delisted
Error: BILLWIN => index 0 is out of bounds for axis 0 with size 0

are you aware of this issue, if so how do you solve this?

Best,
Nikul

**Comment by QueryType** [comment]
These seem to be only BSE listed stock. In that case, you need to to have ".BO" instead of ".NS".
